vim.lsp.enable('solargraph')
-- vim.lsp.config('solargraph', {
  -- cmd = { os.getenv( "HOME" ) .. "solargraph", 'stdio' },
  -- root_dir = vim.lsp.util.root_pattern("Gemfile", ".git", "."),
  -- settings = {
    -- solargraph = {
      -- autoformat = false,
      -- formatting = true,
      -- completion = true,
      -- diagnostic = true,
      -- folding = true,
      -- references = true,
      -- rename = true,
      -- symbols = true
    -- }
  -- }
-- })
